bundler_args: --without yard guard metrics benchmarks

branches:
  only:
    - master
    - /^release-.*$/

services:
  - sqlite3
  - mysql
  - postgresql

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y postgresql-server-dev-all

before_script:
  - mysql -e "create database datamapper_alternate_tests;"
  - mysql -e "create database datamapper_default_tests;"
  - psql  -c "create database datamapper_default_tests;" -U postgres
  - psql  -c "create database datamapper_alternate_tests;" -U postgres

script: "bundle exec rake spec"

rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode

env:
  - "ADAPTER=in_memory"
  - "ADAPTER=yaml"
  - "ADAPTER=sqlite"
  - "ADAPTER=mysql DM_DB_USER=root DM_DB_PASSWORD=''"
  - "ADAPTER=postgres DM_DB_USER=postgres DM_DB_PASSWORD=''"

notifications:
  irc: "irc.freenode.org#datamapper"
  email:
    - dan.kubb@gmail.com

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-19mode
      env: "GIT_BRANCH=release-1.2 ADAPTER=in_memory"
    - rvm: rbx-19mode
      env: "GIT_BRANCH=release-1.2 ADAPTER=yaml"
